### ISSUE TITLE
Closing Payment Channel: Assertion Error

### ISSUE THREAD

**Issue by granuz88** [interledgerjs/moneyd-uplink-xrp#28]
I have the latest version of moneyd and moneyd-uplink-xrp.
I have one channel "ready to close", I lounche the command "moneyd xrp:cleanup", I select the channel to close, but when I press Enter the following error appear:

> fatal: { AssertionError [ERR_ASSERTION]: parameter store must be object
>     at new TransactionFactory (/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-xrp-paychan-shared/lib/transaction-factory.js:8:5)
>     at new TxSubmitter (/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-xrp-paychan-shared/lib/tx-submitter.js:36:23)
>     at module.exports (/usr/lib/node_modules/moneyd-uplink-xrp/node_modules/ilp-plugin-xrp-paychan-shared/lib/tx-submitter.js:213:22)
>     at XrpUplink._submitter (/usr/lib/node_modules/moneyd-uplink-xrp/index.js:235:12)
>   generatedMessage: false,
>   name: 'AssertionError [ERR_ASSERTION]',
>   code: 'ERR_ASSERTION',
>   actual: false,
>   expected: true,
>   operator: '==' }
> 

The operating system is: CentOS Linux release 7.5.1804 (Core).
Any ideas? Thank you!

**Comment by adamstraube** [comment]
Hi @granuz88 I have the same issue here. Currently on Centos-7.0.1406.
Not sure what to make of this as I was able to do this previously on that machine.

**Comment by granuz88** [comment]
Thank you!
The rollback to version 1.2.3 solves the problem!

**Comment by adrianhopebailie** [comment]
Looks like an issue with an updated dependency https://github.com/interledgerjs/ilp-plugin-xrp-paychan-shared/compare/v3.0.3...master which introduced persistence for the tx submitter.

Investigating and will release a patch shortly.

**Comment by traviscrist** [comment]
This should now be resolved in v1.2.5
