### ISSUE TITLE
Regular key support instead of Secret

### ISSUE THREAD

**Issue by sharafian** [interledgerjs/moneyd-uplink-xrp#5]
Moved from https://github.com/interledgerjs/moneyd/issues/50

> Hey
>
> is moneyd support Regular key instead of ripple Secret ?
>
> xrp-community/codius-install#6
> 
> Thanks

**Comment by adrianhopebailie** [comment]
Not sure I understand the question but if it is what I think:

`moneyd` needs to be able to send money so it needs the secret to be able to sign transactions. 

It is able to derive the address from the secret so it doesn't need the address once it has the secret.

**Comment by sharafian** [comment]
https://developers.ripple.com/assign-a-regular-key-pair.html
